### ISSUE TITLE
Example in the README doesn't work

### ISSUE THREAD

**Issue by tmaillart** [BurntSushi/imdb-rename#4]
Hi,

I foolishly get the latest release (0.1.1) and run one of the example of the README (L106)
```
# ~/Desktop/imdb-rename/imdb-rename Ghost.in.the.Shell.MULTI.1080p.Bluray.x264-BG.mkv
[skipping] error searching for Ghost.in.the.Shell.MULTI.1080p.Bluray.x264-BG.mkv: could not parse file path and there is no override set via -q/--query
no files to rename
```
Could someone tell me what's missing, please ?

**Comment by BurntSushi** [comment]
Please note the error message: could not parse file path **and there is no override set via -q/--query**.

imdb-rename uses a number of heuristics to determine matching titles. One of those heuristics is to extract the year from the file path. Without that, imdb-rename doesn't know what kind of media entity it is, so it gives up. You can override the behavior by specifying an explicit `--query`. e.g.,

```
$ imdb-rename -q 'ghost in the shell' Ghost.in.the.Shell.MULTI.1080p.Bluray.x264-BG.mkv
```

**Comment by tmaillart** [comment]
Thank you for the quick reply.

Would it be possible to add more information in the error message, to get the cause of the error like `could not parse ..., missing date` ?

**Comment by BurntSushi** [comment]
@tmaillart That seems reasonable, but I don't know when I'll have time for it. The error message does need to remain short though, since it is emitted for every file path that is skipped. In particular, `imdb-rename` is built to operate on a very large number of files in one go, including crawling directories, and that usually requires skipping a number of miscellaneous files.
